name: haskell
dependencies:
  - base
  - text
  - mysql-haskell
  - io-streams
license: MIT

executable:
  source-dirs:
    app
    src
  main: Main.hs
  other-modules:
    Lim.Echo
    Authentication.User
